dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-02/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: NBHniUlt9HRZZjo0DdSvS8EQJLHoZkRCj/auXFRfjXjBw41o6Hqt7a2BNzqVEA8Pi24vD9MY6iOkVTt3zaZhGoD2sejkU91mTdMD+sI7ML1SWC5Cw1Um43OJHwW6TTtYWmxnvE+kybkStRoSCRAuFqATjn05hlRm15ZKnzTtZcvgWPGbM1kinHFnI+pmpA0zyFia3PcXOFlYUpfBfY7fynUWIQ7g9FROcCSC0nN4FTlnShzBZwFj6MgC1LUXkqSgZvsgTem+0jv3OCzzNmACj14PwrKEHCfSAFEpK4vfAYTkKjIr6/ReTxteCT2tXt5WFwW/qwmE57zo7rv7eQbTUTUajnScce4GT8lcq9zNUzMbcHbOT8B+/GMWD+JvdeK/xvX9ZniE/i6p4ULJuXb6Bic0u5FHZ0XvRiNvzVYlP1M3VwHgNSh8RSv5ihyHkO2gpOMrC9P5S+RfyXlpR6h9V0vYivkXaJq5y/g8ZtugJQ3i9SavskbeeHCqpUvtlLWg0BPTY1EeDlMUzp76sREf653ETfdQ7XNtcCb6HWO0Y1FK5XiVmfFrae3L9dijyNC9N4PVvr2qPVgfMubGAHt7LJItTJTF2DLQRGt014ToHnFDDkJtoqPT7kEq6cbSJFGDxIFDjkxcOhIfIgb6OuLe9zbJl/EhhhPmbuJShvTxrto=
