dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-02/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: pym1E+hhkUGeS1Efw2T0v7Da4FlRiy80CyDitoxNbFmhoy/uMY8/hbHg91TXVPcYPrkZVsGjfI7G2BwMmz2766SixdzDhL3Iq5dkL+eXZRj/mwH6A68P1SSeQRccjp/NMKD7Z/KWglXIsIdaxmktLucDQY32mR8/+H4IlqjrCZ5WstVzPyE8kszyhe7hhT90SD3AQeE8QJMZiu0JcaJYF9axCCBnCxtQ5Dlv7xpaAtcIs1hso5kqju1UAjZKISBkgTCdqD9MtQGsUQigNW84Tn4Aq26pEgyLPjTNCJnIVHnbHuw+5Dr05PF00E6HgVl8/Xe5BZXEkbD3+VyII5jn0KrQhrahzTwbfa+dylzObVXZB2BPBDdprImsZ/N36lEyJJTHBl4MFdEH633bTtAztUSDzvu8ij7aXaklo/viiCPuw8fLZKUy/xp9VQ1rL4UsGLY8h4s087cFYuOMu2aSmmjsd2mAW7xPHJNOCwrmWzrLFZvqMZuh6ox2HfmS0wek5Y1kaADCbLRnVBhCb6MAWVCZf+1BPwWTrlty1EqgS+IwuuN9h4fb7UZbIGeOC0oeTKfRKrD5k3NoJEeSu2dhS8FZciJu2Fned7zmhQz3xW5NF24kznpUmBiBK/GOGi5YWXBFzMm5FxEQnevXyzKx1RSE3KDNCWVz6RkjYmviyeY=
