comment:
  image:
    repository: prostef/comment
    tag: latest
  service:
    externalPort: 9292

post:
  image:
    repository: prostef/post
    tag: latest
  service:
    externalPort: 5000

ui:
  image:
    repository: prostef/ui
    tag: latest
  service:
    externalPort: 9292
