global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
    - channel: '#igor_mokeev'
