version: '3.3'

services:
  post_db:
    image: mongo:${MONGO_VERSION:-latest}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db

  ui:
    image: ${USER_NAME}/ui:${UI_VERSION:-latest}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    ports:
      - ${UI_PORT}:${REDDIT_PORT}/tcp
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
    networks:
      - front_net

  post:
    image: ${USER_NAME}/post:${POST_VERSION:-latest}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    depends_on:
      - post_db
    ports:
      - "5000:5000"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    networks:
      - back_net
      - front_net

  comment:
    image: ${USER_NAME}/comment:${COMMENT_VERSION:-latest}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      - back_net
      - front_net

volumes:
  post_db:

networks:
  back_net:
    internal: true
  front_net:
