{
 "title": "UI_Service_Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Env", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  {
   "title": "UI HTTP Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ui_request_count{kubernetes_namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "HTTP Response Time 95th percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(ui_request_response_time_bucket{kubernetes_namespace=~\"$namespace\"}[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Rate of UI HTTP Requests with Error",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ui_request_count{http_status=~\"^[45].*\", kubernetes_namespace=~\"$namespace\"}[1m])"
    }
   ]
  },
  {
   "title": "Rate of UI HTTP Requests with Success",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ui_request_count{http_status=~\"200\", kubernetes_namespace=~\"$namespace\"}[1m])"
    }
   ]
  }
 ]
}