version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      - reddit
  ui:
    build: ./ui
    image: ${USER_NAME}/ui:${UI_VERSION}
    ports:
      - ${UI_PORT}:${REDDIT_PORT}/tcp
    networks:
      - reddit
  post:
    build: ./post-py
    image: ${USER_NAME}/post:${POST_VERSION}
    networks:
      - reddit
  comment:
    build: ./comment
    image: ${USER_NAME}/comment:${COMMENT_VERSION}
    networks:
      - reddit

volumes:
  post_db:

networks:
  reddit:
